import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// ═══════════════════════════════════════════════════════════════
// MARQUEE PLAYERS — Verified stats from IPL career records
// ═══════════════════════════════════════════════════════════════
const marqueePlayers = [
  { name: "Virat Kohli", nationality: "India", isOverseas: false, role: "Batsman", specialization: "Right-hand Bat", basePrice: 200, tier: "Marquee", stats: { matches: 237, runs: 7263, battingAvg: 37.25, strikeRate: 130.41, wickets: 4, bowlingAvg: 166, economy: 8.83, catches: 109, fifties: 50, hundreds: 7 }},
  { name: "Rohit Sharma", nationality: "India", isOverseas: false, role: "Batsman", specialization: "Right-hand Bat", basePrice: 200, tier: "Marquee", stats: { matches: 244, runs: 6211, battingAvg: 29.21, strikeRate: 130.04, wickets: 15, bowlingAvg: 32.13, economy: 7.96, catches: 102, fifties: 42, hundreds: 2 }},
  { name: "Jasprit Bumrah", nationality: "India", isOverseas: false, role: "Bowler", specialization: "Right-arm Fast", basePrice: 200, tier: "Marquee", stats: { matches: 133, runs: 56, battingAvg: 5.6, strikeRate: 88.89, wickets: 163, bowlingAvg: 23.45, economy: 7.39, catches: 18, fifties: 0, hundreds: 0 }},
  { name: "MS Dhoni", nationality: "India", isOverseas: false, role: "Wicketkeeper", specialization: "Right-hand Bat, WK", basePrice: 200, tier: "Marquee", stats: { matches: 264, runs: 5243, battingAvg: 38.09, strikeRate: 135.91, wickets: 0, bowlingAvg: 0, economy: 0, catches: 120, fifties: 24, hundreds: 0 }},
  { name: "Rashid Khan", nationality: "Afghanistan", isOverseas: true, role: "Bowler", specialization: "Right-arm Leg Spin", basePrice: 200, tier: "Marquee", stats: { matches: 109, runs: 474, battingAvg: 15.8, strikeRate: 147.35, wickets: 130, bowlingAvg: 20.3, economy: 6.55, catches: 32, fifties: 0, hundreds: 0 }},
  { name: "Suryakumar Yadav", nationality: "India", isOverseas: false, role: "Batsman", specialization: "Right-hand Bat", basePrice: 200, tier: "Marquee", stats: { matches: 125, runs: 3540, battingAvg: 32.78, strikeRate: 145.96, wickets: 0, bowlingAvg: 0, economy: 0, catches: 52, fifties: 24, hundreds: 1 }},
  { name: "Rishabh Pant", nationality: "India", isOverseas: false, role: "Wicketkeeper", specialization: "Left-hand Bat, WK", basePrice: 200, tier: "Marquee", stats: { matches: 111, runs: 3284, battingAvg: 34.93, strikeRate: 149.07, wickets: 0, bowlingAvg: 0, economy: 0, catches: 65, fifties: 18, hundreds: 1 }},
  { name: "Shreyas Iyer", nationality: "India", isOverseas: false, role: "Batsman", specialization: "Right-hand Bat", basePrice: 200, tier: "Marquee", stats: { matches: 115, runs: 3127, battingAvg: 32.57, strikeRate: 126.68, wickets: 0, bowlingAvg: 0, economy: 0, catches: 48, fifties: 20, hundreds: 1 }},
  { name: "Jos Buttler", nationality: "England", isOverseas: true, role: "Wicketkeeper", specialization: "Right-hand Bat, WK", basePrice: 200, tier: "Marquee", stats: { matches: 82, runs: 2831, battingAvg: 38.79, strikeRate: 149.07, wickets: 0, bowlingAvg: 0, economy: 0, catches: 33, fifties: 16, hundreds: 6 }},
  { name: "KL Rahul", nationality: "India", isOverseas: false, role: "Wicketkeeper", specialization: "Right-hand Bat, WK", basePrice: 200, tier: "Marquee", stats: { matches: 118, runs: 4019, battingAvg: 37.56, strikeRate: 133.28, wickets: 0, bowlingAvg: 0, economy: 0, catches: 42, fifties: 33, hundreds: 4 }},
  { name: "Ravindra Jadeja", nationality: "India", isOverseas: false, role: "All-Rounder", specialization: "Left-hand Bat, Left-arm Spin", basePrice: 200, tier: "Marquee", stats: { matches: 226, runs: 2692, battingAvg: 26.39, strikeRate: 127.23, wickets: 152, bowlingAvg: 28.94, economy: 7.59, catches: 87, fifties: 5, hundreds: 0 }},
  { name: "Hardik Pandya", nationality: "India", isOverseas: false, role: "All-Rounder", specialization: "Right-hand Bat, Right-arm Fast Medium", basePrice: 200, tier: "Marquee", stats: { matches: 120, runs: 2340, battingAvg: 28.78, strikeRate: 147.52, wickets: 57, bowlingAvg: 31.58, economy: 9.04, catches: 45, fifties: 7, hundreds: 1 }},
  { name: "Shubman Gill", nationality: "India", isOverseas: false, role: "Batsman", specialization: "Right-hand Bat", basePrice: 200, tier: "Marquee", stats: { matches: 82, runs: 2592, battingAvg: 35.02, strikeRate: 131.98, wickets: 0, bowlingAvg: 0, economy: 0, catches: 39, fifties: 18, hundreds: 3 }},
  { name: "Yashasvi Jaiswal", nationality: "India", isOverseas: false, role: "Batsman", specialization: "Left-hand Bat", basePrice: 200, tier: "Marquee", stats: { matches: 36, runs: 1252, battingAvg: 37.93, strikeRate: 161.23, wickets: 0, bowlingAvg: 0, economy: 0, catches: 16, fifties: 8, hundreds: 3 }},
  { name: "Sanju Samson", nationality: "India", isOverseas: false, role: "Wicketkeeper", specialization: "Right-hand Bat, WK", basePrice: 200, tier: "Marquee", stats: { matches: 137, runs: 3326, battingAvg: 28.67, strikeRate: 137.35, wickets: 0, bowlingAvg: 0, economy: 0, catches: 55, fifties: 17, hundreds: 3 }},
  { name: "Ruturaj Gaikwad", nationality: "India", isOverseas: false, role: "Batsman", specialization: "Right-hand Bat", basePrice: 200, tier: "Marquee", stats: { matches: 64, runs: 2242, battingAvg: 38.65, strikeRate: 136.15, wickets: 0, bowlingAvg: 0, economy: 0, catches: 26, fifties: 15, hundreds: 2 }},
  { name: "Heinrich Klaasen", nationality: "South Africa", isOverseas: true, role: "Wicketkeeper", specialization: "Right-hand Bat, WK", basePrice: 200, tier: "Marquee", stats: { matches: 32, runs: 1173, battingAvg: 42.96, strikeRate: 175.15, wickets: 0, bowlingAvg: 0, economy: 0, catches: 13, fifties: 7, hundreds: 2 }},
  { name: "Pat Cummins", nationality: "Australia", isOverseas: true, role: "All-Rounder", specialization: "Right-arm Fast", basePrice: 200, tier: "Marquee", stats: { matches: 45, runs: 234, battingAvg: 14.62, strikeRate: 128.57, wickets: 45, bowlingAvg: 29.78, economy: 8.72, catches: 12, fifties: 0, hundreds: 0 }},
  { name: "Mitchell Starc", nationality: "Australia", isOverseas: true, role: "Bowler", specialization: "Left-arm Fast", basePrice: 200, tier: "Marquee", stats: { matches: 28, runs: 52, battingAvg: 8.67, strikeRate: 104.0, wickets: 35, bowlingAvg: 28.14, economy: 9.24, catches: 5, fifties: 0, hundreds: 0 }},
  { name: "Kagiso Rabada", nationality: "South Africa", isOverseas: true, role: "Bowler", specialization: "Right-arm Fast", basePrice: 200, tier: "Marquee", stats: { matches: 63, runs: 57, battingAvg: 6.33, strikeRate: 91.93, wickets: 79, bowlingAvg: 24.05, economy: 8.31, catches: 12, fifties: 0, hundreds: 0 }},
];

// ═══════════════════════════════════════════════════════════════
// TIER A — Star internationals and experienced IPL players
// ═══════════════════════════════════════════════════════════════
const tierAPlayers = [
  // Indian Stars
  { name: "Ravichandran Ashwin", role: "All-Rounder", spec: "Right-arm Off Spin", overseas: false },
  { name: "Yuzvendra Chahal", role: "Bowler", spec: "Right-arm Leg Spin", overseas: false },
  { name: "Mohammed Siraj", role: "Bowler", spec: "Right-arm Fast", overseas: false },
  { name: "Mohammed Shami", role: "Bowler", spec: "Right-arm Fast Medium", overseas: false },
  { name: "Kuldeep Yadav", role: "Bowler", spec: "Left-arm Chinaman", overseas: false },
  { name: "Axar Patel", role: "All-Rounder", spec: "Left-arm Spin", overseas: false },
  { name: "Ishan Kishan", role: "Wicketkeeper", spec: "Left-hand Bat, WK", overseas: false },
  { name: "Devdutt Padikkal", role: "Batsman", spec: "Left-hand Bat", overseas: false },
  { name: "Arshdeep Singh", role: "Bowler", spec: "Left-arm Fast Medium", overseas: false },
  { name: "Harshal Patel", role: "Bowler", spec: "Right-arm Medium", overseas: false },
  { name: "Washington Sundar", role: "All-Rounder", spec: "Left-hand Bat, Right-arm Off Spin", overseas: false },
  { name: "Venkatesh Iyer", role: "All-Rounder", spec: "Left-hand Bat, Right-arm Medium", overseas: false },
  { name: "Tilak Varma", role: "Batsman", spec: "Left-hand Bat", overseas: false },
  { name: "Rinku Singh", role: "Batsman", spec: "Left-hand Bat", overseas: false },
  { name: "Abhishek Sharma", role: "All-Rounder", spec: "Left-hand Bat, Left-arm Spin", overseas: false },
  { name: "Nitish Kumar Reddy", role: "All-Rounder", spec: "Right-hand Bat, Right-arm Medium", overseas: false },
  // Overseas Stars
  { name: "David Warner", role: "Batsman", spec: "Left-hand Bat", overseas: true, nat: "Australia" },
  { name: "Glenn Maxwell", role: "All-Rounder", spec: "Right-hand Bat, Right-arm Off Spin", overseas: true, nat: "Australia" },
  { name: "Trent Boult", role: "Bowler", spec: "Left-arm Fast", overseas: true, nat: "New Zealand" },
  { name: "Quinton de Kock", role: "Wicketkeeper", spec: "Left-hand Bat, WK", overseas: true, nat: "South Africa" },
  { name: "Faf du Plessis", role: "Batsman", spec: "Right-hand Bat", overseas: true, nat: "South Africa" },
  { name: "Kane Williamson", role: "Batsman", spec: "Right-hand Bat", overseas: true, nat: "New Zealand" },
  { name: "Liam Livingstone", role: "All-Rounder", spec: "Right-hand Bat, Right-arm Leg Spin", overseas: true, nat: "England" },
  { name: "David Miller", role: "Batsman", spec: "Left-hand Bat", overseas: true, nat: "South Africa" },
  { name: "Marcus Stoinis", role: "All-Rounder", spec: "Right-hand Bat, Right-arm Medium", overseas: true, nat: "Australia" },
  { name: "Sam Curran", role: "All-Rounder", spec: "Left-hand Bat, Left-arm Medium", overseas: true, nat: "England" },
  { name: "Marco Jansen", role: "All-Rounder", spec: "Left-hand Bat, Left-arm Fast", overseas: true, nat: "South Africa" },
  { name: "Josh Hazlewood", role: "Bowler", spec: "Right-arm Fast", overseas: true, nat: "Australia" },
  { name: "Rachin Ravindra", role: "All-Rounder", spec: "Left-hand Bat, Left-arm Spin", overseas: true, nat: "New Zealand" },
  { name: "Travis Head", role: "Batsman", spec: "Left-hand Bat", overseas: true, nat: "Australia" },
  { name: "Phil Salt", role: "Wicketkeeper", spec: "Right-hand Bat, WK", overseas: true, nat: "England" },
  { name: "Jonny Bairstow", role: "Wicketkeeper", spec: "Right-hand Bat, WK", overseas: true, nat: "England" },
  { name: "Wanindu Hasaranga", role: "All-Rounder", spec: "Right-arm Leg Spin", overseas: true, nat: "Sri Lanka" },
  { name: "Anrich Nortje", role: "Bowler", spec: "Right-arm Fast", overseas: true, nat: "South Africa" },
  { name: "Mitchell Marsh", role: "All-Rounder", spec: "Right-hand Bat, Right-arm Fast Medium", overseas: true, nat: "Australia" },
  { name: "Harry Brook", role: "Batsman", spec: "Right-hand Bat", overseas: true, nat: "England" },
  { name: "Devon Conway", role: "Batsman", spec: "Left-hand Bat", overseas: true, nat: "New Zealand" },
  { name: "Lockie Ferguson", role: "Bowler", spec: "Right-arm Fast", overseas: true, nat: "New Zealand" },
  { name: "Gerald Coetzee", role: "Bowler", spec: "Right-arm Fast", overseas: true, nat: "South Africa" },
  { name: "Nandre Burger", role: "Bowler", spec: "Left-arm Fast", overseas: true, nat: "South Africa" },
  { name: "Spencer Johnson", role: "Bowler", spec: "Left-arm Fast", overseas: true, nat: "Australia" },
  { name: "Maheesh Theekshana", role: "Bowler", spec: "Right-arm Off Spin", overseas: true, nat: "Sri Lanka" },
  { name: "Adam Zampa", role: "Bowler", spec: "Right-arm Leg Spin", overseas: true, nat: "Australia" },
  { name: "Jake Fraser-McGurk", role: "Batsman", spec: "Right-hand Bat", overseas: true, nat: "Australia" },
];

// ═══════════════════════════════════════════════════════════════
// TIER B — Established domestic & international players
// ═══════════════════════════════════════════════════════════════
const tierBNames = [
  // Indian - B tier
  { name: "Shardul Thakur", role: "All-Rounder", spec: "Right-arm Fast Medium", overseas: false },
  { name: "Krunal Pandya", role: "All-Rounder", spec: "Left-arm Spin", overseas: false },
  { name: "Deepak Chahar", role: "Bowler", spec: "Right-arm Medium Fast", overseas: false },
  { name: "Bhuvneshwar Kumar", role: "Bowler", spec: "Right-arm Medium Fast", overseas: false },
  { name: "Khaleel Ahmed", role: "Bowler", spec: "Left-arm Fast Medium", overseas: false },
  { name: "Avesh Khan", role: "Bowler", spec: "Right-arm Fast", overseas: false },
  { name: "Prasidh Krishna", role: "Bowler", spec: "Right-arm Fast", overseas: false },
  { name: "Rahul Chahar", role: "Bowler", spec: "Right-arm Leg Spin", overseas: false },
  { name: "Mukesh Kumar", role: "Bowler", spec: "Right-arm Fast Medium", overseas: false },
  { name: "Akash Deep", role: "Bowler", spec: "Right-arm Fast Medium", overseas: false },
  { name: "T Natarajan", role: "Bowler", spec: "Left-arm Fast Medium", overseas: false },
  { name: "Rahul Tripathi", role: "Batsman", spec: "Right-hand Bat", overseas: false },
  { name: "Nitish Rana", role: "Batsman", spec: "Left-hand Bat", overseas: false },
  { name: "Prithvi Shaw", role: "Batsman", spec: "Right-hand Bat", overseas: false },
  { name: "Ajinkya Rahane", role: "Batsman", spec: "Right-hand Bat", overseas: false },
  { name: "Mayank Agarwal", role: "Batsman", spec: "Right-hand Bat", overseas: false },
  { name: "Karun Nair", role: "Batsman", spec: "Right-hand Bat", overseas: false },
  { name: "Manish Pandey", role: "Batsman", spec: "Right-hand Bat", overseas: false },
  { name: "Sai Sudharsan", role: "Batsman", spec: "Left-hand Bat", overseas: false },
  { name: "Shivam Dube", role: "All-Rounder", spec: "Left-hand Bat, Right-arm Medium", overseas: false },
  { name: "Vijay Shankar", role: "All-Rounder", spec: "Right-hand Bat, Right-arm Medium", overseas: false },
  { name: "Shahbaz Ahmed", role: "All-Rounder", spec: "Left-hand Bat, Left-arm Spin", overseas: false },
  { name: "Deepak Hooda", role: "All-Rounder", spec: "Right-hand Bat, Right-arm Off Spin", overseas: false },
  { name: "Rahul Tewatia", role: "All-Rounder", spec: "Left-hand Bat, Right-arm Leg Spin", overseas: false },
  { name: "Shahrukh Khan", role: "Batsman", spec: "Right-hand Bat", overseas: false },
  { name: "Ravi Bishnoi", role: "Bowler", spec: "Right-arm Leg Spin", overseas: false },
  { name: "Tushar Deshpande", role: "Bowler", spec: "Right-arm Fast Medium", overseas: false },
  { name: "Mayank Yadav", role: "Bowler", spec: "Right-arm Fast", overseas: false },
  { name: "Umran Malik", role: "Bowler", spec: "Right-arm Fast", overseas: false },
  { name: "Jitesh Sharma", role: "Wicketkeeper", spec: "Left-hand Bat, WK", overseas: false },
  { name: "Dhruv Jurel", role: "Wicketkeeper", spec: "Right-hand Bat, WK", overseas: false },
  { name: "Rajat Patidar", role: "Batsman", spec: "Right-hand Bat", overseas: false },
  { name: "Ayush Badoni", role: "Batsman", spec: "Right-hand Bat", overseas: false },
  { name: "Shashank Singh", role: "Batsman", spec: "Right-hand Bat", overseas: false },
  // Overseas - B tier
  { name: "Rovman Powell", role: "Batsman", spec: "Right-hand Bat", overseas: true, nat: "West Indies" },
  { name: "Glenn Phillips", role: "Batsman", spec: "Right-hand Bat", overseas: true, nat: "New Zealand" },
  { name: "Aiden Markram", role: "Batsman", spec: "Right-hand Bat", overseas: true, nat: "South Africa" },
  { name: "Daryl Mitchell", role: "All-Rounder", spec: "Right-hand Bat, Right-arm Medium", overseas: true, nat: "New Zealand" },
  { name: "Moeen Ali", role: "All-Rounder", spec: "Left-hand Bat, Right-arm Off Spin", overseas: true, nat: "England" },
  { name: "Tim David", role: "All-Rounder", spec: "Right-hand Bat", overseas: true, nat: "Australia" },
  { name: "Will Jacks", role: "All-Rounder", spec: "Right-hand Bat, Right-arm Off Spin", overseas: true, nat: "England" },
  { name: "Rahmanullah Gurbaz", role: "Wicketkeeper", spec: "Right-hand Bat, WK", overseas: true, nat: "Afghanistan" },
  { name: "Tristan Stubbs", role: "Batsman", spec: "Right-hand Bat", overseas: true, nat: "South Africa" },
  { name: "Alzarri Joseph", role: "Bowler", spec: "Right-arm Fast", overseas: true, nat: "West Indies" },
  { name: "Fazalhaq Farooqi", role: "Bowler", spec: "Left-arm Fast", overseas: true, nat: "Afghanistan" },
  { name: "Mustafizur Rahman", role: "Bowler", spec: "Left-arm Fast Medium", overseas: true, nat: "Bangladesh" },
  { name: "Naveen-ul-Haq", role: "Bowler", spec: "Right-arm Fast Medium", overseas: true, nat: "Afghanistan" },
  { name: "Adil Rashid", role: "Bowler", spec: "Right-arm Leg Spin", overseas: true, nat: "England" },
  { name: "Matheesha Pathirana", role: "Bowler", spec: "Right-arm Fast", overseas: true, nat: "Sri Lanka" },
  { name: "Rilee Rossouw", role: "Batsman", spec: "Left-hand Bat", overseas: true, nat: "South Africa" },
  { name: "Azmatullah Omarzai", role: "All-Rounder", spec: "Right-hand Bat, Right-arm Fast Medium", overseas: true, nat: "Afghanistan" },
  { name: "Romario Shepherd", role: "All-Rounder", spec: "Right-hand Bat, Right-arm Fast Medium", overseas: true, nat: "West Indies" },
  { name: "Alex Carey", role: "Wicketkeeper", spec: "Left-hand Bat, WK", overseas: true, nat: "Australia" },
  { name: "Shai Hope", role: "Wicketkeeper", spec: "Right-hand Bat, WK", overseas: true, nat: "West Indies" },
  { name: "Steven Smith", role: "Batsman", spec: "Right-hand Bat", overseas: true, nat: "Australia" },
  { name: "Mitchell Santner", role: "All-Rounder", spec: "Left-hand Bat, Left-arm Spin", overseas: true, nat: "New Zealand" },
  { name: "Keshav Maharaj", role: "Bowler", spec: "Left-arm Spin", overseas: true, nat: "South Africa" },
  { name: "Lungi Ngidi", role: "Bowler", spec: "Right-arm Fast", overseas: true, nat: "South Africa" },
  { name: "Reece Topley", role: "Bowler", spec: "Left-arm Fast Medium", overseas: true, nat: "England" },
  { name: "Matt Henry", role: "Bowler", spec: "Right-arm Fast Medium", overseas: true, nat: "New Zealand" },
  { name: "Kwena Maphaka", role: "Bowler", spec: "Left-arm Fast", overseas: true, nat: "South Africa" },
  { name: "Donovan Ferreira", role: "Batsman", spec: "Right-hand Bat", overseas: true, nat: "South Africa" },
  { name: "Ryan Rickelton", role: "Batsman", spec: "Left-hand Bat", overseas: true, nat: "South Africa" },
  { name: "Josh Inglis", role: "Wicketkeeper", spec: "Right-hand Bat, WK", overseas: true, nat: "Australia" },
  { name: "Noor Ahmad", role: "Bowler", spec: "Left-arm Chinaman", overseas: true, nat: "Afghanistan" },
];

// ═══════════════════════════════════════════════════════════════
// TIER C — Domestic and uncapped players (bulk of the pool)
// ═══════════════════════════════════════════════════════════════
const tierCNames = [
  // Indian domestic
  { name: "Yash Dhull", role: "Batsman", overseas: false },
  { name: "Abhinav Manohar", role: "Batsman", overseas: false },
  { name: "Angkrish Raghuvanshi", role: "Batsman", overseas: false },
  { name: "Anmolpreet Singh", role: "Batsman", overseas: false },
  { name: "Atharva Taide", role: "Batsman", overseas: false },
  { name: "Harpreet Brar", role: "All-Rounder", overseas: false },
  { name: "Naman Dhir", role: "Batsman", overseas: false },
  { name: "Mahipal Lomror", role: "All-Rounder", overseas: false },
  { name: "Sameer Rizvi", role: "Batsman", overseas: false },
  { name: "Abdul Samad", role: "Batsman", overseas: false },
  { name: "Ashutosh Sharma", role: "All-Rounder", overseas: false },
  { name: "Nishant Sindhu", role: "All-Rounder", overseas: false },
  { name: "Utkarsh Singh", role: "Batsman", overseas: false },
  { name: "Aryan Juyal", role: "Wicketkeeper", overseas: false },
  { name: "Kumar Kushagra", role: "Wicketkeeper", overseas: false },
  { name: "Robin Minz", role: "Wicketkeeper", overseas: false },
  { name: "Anuj Rawat", role: "Wicketkeeper", overseas: false },
  { name: "Luvnith Sisodia", role: "Wicketkeeper", overseas: false },
  { name: "Vishnu Vinod", role: "Wicketkeeper", overseas: false },
  { name: "Vaibhav Arora", role: "Bowler", overseas: false },
  { name: "Rasikh Dar", role: "Bowler", overseas: false },
  { name: "Akash Madhwal", role: "Bowler", overseas: false },
  { name: "Mohit Sharma", role: "Bowler", overseas: false },
  { name: "Simarjeet Singh", role: "Bowler", overseas: false },
  { name: "Yash Thakur", role: "Bowler", overseas: false },
  { name: "Kartik Tyagi", role: "Bowler", overseas: false },
  { name: "Vyshak Vijaykumar", role: "Bowler", overseas: false },
  { name: "Piyush Chawla", role: "Bowler", overseas: false },
  { name: "Shreyas Gopal", role: "Bowler", overseas: false },
  { name: "Mayank Markande", role: "Bowler", overseas: false },
  { name: "Suyash Sharma", role: "Bowler", overseas: false },
  { name: "Karn Sharma", role: "Bowler", overseas: false },
  { name: "Kumar Kartikeya Singh", role: "Bowler", overseas: false },
  { name: "Manav Suthar", role: "Bowler", overseas: false },
  { name: "Ricky Bhui", role: "Batsman", overseas: false },
  { name: "Swastik Chhikara", role: "Batsman", overseas: false },
  { name: "Nehal Wadhera", role: "Batsman", overseas: false },
  { name: "Shubham Dubey", role: "Batsman", overseas: false },
  { name: "Madhav Kaushik", role: "Batsman", overseas: false },
  { name: "Pukhraj Mann", role: "Batsman", overseas: false },
  { name: "Shaik Rasheed", role: "Batsman", overseas: false },
  { name: "Himmat Singh", role: "Batsman", overseas: false },
  { name: "Mayank Dagar", role: "All-Rounder", overseas: false },
  { name: "Anshul Kamboj", role: "All-Rounder", overseas: false },
  { name: "Darshan Nalkande", role: "All-Rounder", overseas: false },
  { name: "Suyash Prabhudessai", role: "All-Rounder", overseas: false },
  { name: "Anukul Roy", role: "All-Rounder", overseas: false },
  { name: "Swapnil Singh", role: "All-Rounder", overseas: false },
  { name: "Sanvir Singh", role: "All-Rounder", overseas: false },
  { name: "Gurnoor Singh Brar", role: "Bowler", overseas: false },
  { name: "Mukesh Choudhary", role: "Bowler", overseas: false },
  { name: "Sakib Hussain", role: "Bowler", overseas: false },
  { name: "Vidwath Kaverappa", role: "Bowler", overseas: false },
  { name: "Rajan Kumar", role: "Bowler", overseas: false },
  { name: "Sushant Mishra", role: "Bowler", overseas: false },
  { name: "Arjun Tendulkar", role: "All-Rounder", overseas: false },
  { name: "Prashant Solanki", role: "All-Rounder", overseas: false },
  { name: "Ishant Sharma", role: "Bowler", overseas: false },
  { name: "Jaydev Unadkat", role: "Bowler", overseas: false },
  { name: "Umesh Yadav", role: "Bowler", overseas: false },
  { name: "Chetan Sakariya", role: "Bowler", overseas: false },
  { name: "Navdeep Saini", role: "Bowler", overseas: false },
  { name: "Sachin Baby", role: "Batsman", overseas: false },
  { name: "Priyam Garg", role: "Batsman", overseas: false },
  { name: "Krishnappa Gowtham", role: "All-Rounder", overseas: false },
  { name: "Jayant Yadav", role: "All-Rounder", overseas: false },
  { name: "Sarfaraz Khan", role: "Batsman", overseas: false },
  { name: "R Sai Kishore", role: "Bowler", overseas: false },
  { name: "Lalit Yadav", role: "All-Rounder", overseas: false },
  { name: "Harshit Rana", role: "Bowler", overseas: false },
  { name: "Shivam Mavi", role: "Bowler", overseas: false },
  { name: "Varun Chakaravarthy", role: "Bowler", overseas: false },
  { name: "Sandeep Sharma", role: "Bowler", overseas: false },
  { name: "Ishan Porel", role: "Bowler", overseas: false },
  { name: "Kamlesh Nagarkoti", role: "Bowler", overseas: false },
  { name: "Basil Thampi", role: "Bowler", overseas: false },
  { name: "Kuldeep Sen", role: "Bowler", overseas: false },
  { name: "Yash Dayal", role: "Bowler", overseas: false },
  { name: "Mohsin Khan", role: "Bowler", overseas: false },
  { name: "Ramandeep Singh", role: "All-Rounder", overseas: false },
  { name: "Prabhsimran Singh", role: "Wicketkeeper", overseas: false },
  { name: "Avanish Aravelly", role: "Wicketkeeper", overseas: false },
  { name: "Vansh Bedi", role: "Wicketkeeper", overseas: false },
  { name: "Saurav Chauhan", role: "Wicketkeeper", overseas: false },
  { name: "Harvik Desai", role: "Wicketkeeper", overseas: false },
  { name: "Kunal Rathore", role: "Wicketkeeper", overseas: false },
  { name: "B.R Sharath", role: "Wicketkeeper", overseas: false },
  { name: "Upendra Singh Yadav", role: "Wicketkeeper", overseas: false },
  { name: "Sachin Dhas", role: "Batsman", overseas: false },
  { name: "Priyansh Arya", role: "All-Rounder", overseas: false },
  { name: "Manoj Bhandage", role: "All-Rounder", overseas: false },
  { name: "Pravin Dubey", role: "All-Rounder", overseas: false },
  { name: "Ajay Mandal", role: "All-Rounder", overseas: false },
  { name: "Prerak Mankad", role: "All-Rounder", overseas: false },
  { name: "Rajvardhan Hangargekar", role: "All-Rounder", overseas: false },
  { name: "Tanush Kotian", role: "All-Rounder", overseas: false },
  { name: "Arshin Kulkarni", role: "All-Rounder", overseas: false },
  { name: "Shams Mulani", role: "All-Rounder", overseas: false },
  { name: "Shivam Singh", role: "All-Rounder", overseas: false },
  { name: "Abhimanyu Easwaran", role: "Batsman", overseas: false },
  { name: "Musheer Khan", role: "All-Rounder", overseas: false },
  { name: "Hrithik Shokeen", role: "All-Rounder", overseas: false },
  { name: "Sandeep Warrier", role: "Bowler", overseas: false },
  { name: "Rishi Dhawan", role: "All-Rounder", overseas: false },
  { name: "Vijayakanth Viyaskanth", role: "Bowler", overseas: false },
  { name: "Murugan Ashwin", role: "Bowler", overseas: false },
  { name: "Jagadeesha Suchith", role: "All-Rounder", overseas: false },
  { name: "Narayan Jagadeesan", role: "Wicketkeeper", overseas: false },
  { name: "Tanmay Agarwal", role: "Batsman", overseas: false },
  { name: "Ayush Mhatre", role: "Batsman", overseas: false },
  { name: "Manan Vohra", role: "Batsman", overseas: false },
  { name: "Samarth Vyas", role: "Batsman", overseas: false },
  { name: "Raj Angad Bawa", role: "All-Rounder", overseas: false },
  { name: "Suryansh Shedge", role: "All-Rounder", overseas: false },
  { name: "Mayank Rawat", role: "Wicketkeeper", overseas: false },
  { name: "Anmol Malhotra", role: "Wicketkeeper", overseas: false },
  { name: "Siddharth Yadav", role: "Bowler", overseas: false },
  { name: "Naman Tiwari", role: "All-Rounder", overseas: false },
  { name: "Vipraj Nigam", role: "All-Rounder", overseas: false },
  { name: "Vicky Ostwal", role: "Bowler", overseas: false },
  { name: "Shivalik Sharma", role: "All-Rounder", overseas: false },
  { name: "Himanshu Chauhan", role: "Batsman", overseas: false },
  { name: "Kuldip Yadav", role: "Bowler", overseas: false },
  { name: "Aman Khan", role: "All-Rounder", overseas: false },
  { name: "Sumit Kumar", role: "Bowler", overseas: false },
  { name: "Harnoor Pannu", role: "Batsman", overseas: false },
  { name: "Shashwat Rawat", role: "Batsman", overseas: false },
  { name: "Apoorv Wankhade", role: "Batsman", overseas: false },
  { name: "Yudhvir Singh Charak", role: "All-Rounder", overseas: false },
  { name: "Mohammed Azharuddeen", role: "Wicketkeeper", overseas: false },
  { name: "Urvil Patel", role: "Wicketkeeper", overseas: false },
  { name: "Money Grewal", role: "Bowler", overseas: false },
  { name: "Ashwani Kumar", role: "Bowler", overseas: false },
  { name: "Abhilash Shetty", role: "Bowler", overseas: false },
  { name: "Akash Singh", role: "Bowler", overseas: false },
  { name: "Gurjapneet Singh", role: "Bowler", overseas: false },
  { name: "Chintal Gandhi", role: "Bowler", overseas: false },
  { name: "Salil Arora", role: "Wicketkeeper", overseas: false },
  { name: "Dinesh Bana", role: "Wicketkeeper", overseas: false },
  { name: "Shrijith Krishnan", role: "Wicketkeeper", overseas: false },
  { name: "K.M Asif", role: "Bowler", overseas: false },
  { name: "Akhil Chaudhary", role: "All-Rounder", overseas: false },
  { name: "Arpit Guleria", role: "Bowler", overseas: false },
  { name: "Nishanth Saranu", role: "All-Rounder", overseas: false },
  { name: "Shubham Agrawal", role: "Batsman", overseas: false },
  { name: "Jassinder Baidwan", role: "Bowler", overseas: false },
  { name: "Pulkit Narang", role: "All-Rounder", overseas: false },
  { name: "Mohit Rathee", role: "Bowler", overseas: false },
  { name: "Himanshu Singh", role: "Bowler", overseas: false },
  { name: "Saurabh Dubey", role: "All-Rounder", overseas: false },
  { name: "Aaqib Khan", role: "Bowler", overseas: false },
  { name: "Kulwant Khejroliya", role: "Bowler", overseas: false },
  { name: "Ankit Singh Rajpoot", role: "Bowler", overseas: false },
  { name: "Divesh Sharma", role: "Bowler", overseas: false },
  { name: "Prince Yadav", role: "Bowler", overseas: false },
  { name: "Kunal Singh Chib", role: "All-Rounder", overseas: false },
  { name: "Yuvraj Chudasama", role: "Batsman", overseas: false },
  { name: "Deepak Devadiga", role: "All-Rounder", overseas: false },
  { name: "Avinash Singh", role: "Bowler", overseas: false },
  { name: "Shivam Shukla", role: "Bowler", overseas: false },
  { name: "Agni Chopra", role: "Batsman", overseas: false },
  { name: "Sudip Gharami", role: "Batsman", overseas: false },
  { name: "Shubham Khajuria", role: "Batsman", overseas: false },
  { name: "Akhil Rawat", role: "Batsman", overseas: false },
  { name: "Prateek Yadav", role: "Batsman", overseas: false },
  { name: "Abdul Bazith", role: "All-Rounder", overseas: false },
  { name: "Yuvraj Chaudhary", role: "All-Rounder", overseas: false },
  { name: "Hardik Raj", role: "All-Rounder", overseas: false },
  { name: "Harsh Tyagi", role: "Bowler", overseas: false },
  { name: "Unmukt Chand", role: "Batsman", overseas: false },
  { name: "Baba Indrajith", role: "Batsman", overseas: false },
  { name: "Baltej Dhanda", role: "Bowler", overseas: false },
  { name: "Prince Choudhary", role: "Bowler", overseas: false },
  { name: "Hemanshu Sharma", role: "All-Rounder", overseas: false },
  { name: "M. Siddharth", role: "Bowler", overseas: false },
  { name: "Digvesh Singh", role: "Bowler", overseas: false },
  { name: "Zeeshan Ansari", role: "Bowler", overseas: false },
  // Overseas C tier
  { name: "Finn Allen", role: "Batsman", overseas: true, nat: "New Zealand" },
  { name: "Dewald Brevis", role: "Batsman", overseas: true, nat: "South Africa" },
  { name: "Ben Duckett", role: "Batsman", overseas: true, nat: "England" },
  { name: "Sherfane Rutherford", role: "Batsman", overseas: true, nat: "West Indies" },
  { name: "Ashton Turner", role: "Batsman", overseas: true, nat: "Australia" },
  { name: "James Vince", role: "Batsman", overseas: true, nat: "England" },
  { name: "Michael Bracewell", role: "All-Rounder", overseas: true, nat: "New Zealand" },
  { name: "Tom Banton", role: "Wicketkeeper", overseas: true, nat: "England" },
  { name: "Sam Billings", role: "Wicketkeeper", overseas: true, nat: "England" },
  { name: "Ben McDermott", role: "Batsman", overseas: true, nat: "Australia" },
  { name: "Kusal Mendis", role: "Wicketkeeper", overseas: true, nat: "Sri Lanka" },
  { name: "Kusal Perera", role: "Batsman", overseas: true, nat: "Sri Lanka" },
  { name: "Josh Philippe", role: "Wicketkeeper", overseas: true, nat: "Australia" },
  { name: "Tim Seifert", role: "Wicketkeeper", overseas: true, nat: "New Zealand" },
  { name: "Rishad Hossain", role: "All-Rounder", overseas: true, nat: "Bangladesh" },
  { name: "Tabraiz Shamsi", role: "Bowler", overseas: true, nat: "South Africa" },
  { name: "Jeffery Vandersay", role: "Bowler", overseas: true, nat: "Sri Lanka" },
  { name: "Tanveer Sangha", role: "Bowler", overseas: true, nat: "Australia" },
  { name: "Sediqullah Atal", role: "Batsman", overseas: true, nat: "Afghanistan" },
  { name: "Matthew Breetzke", role: "Batsman", overseas: true, nat: "South Africa" },
  { name: "Mark Chapman", role: "Batsman", overseas: true, nat: "New Zealand" },
  { name: "Brandon King", role: "Batsman", overseas: true, nat: "West Indies" },
  { name: "Evin Lewis", role: "Batsman", overseas: true, nat: "West Indies" },
  { name: "Pathum Nissanka", role: "Batsman", overseas: true, nat: "Sri Lanka" },
  { name: "Bhanuka Rajapaksa", role: "Batsman", overseas: true, nat: "Sri Lanka" },
  { name: "Gus Atkinson", role: "All-Rounder", overseas: true, nat: "England" },
  { name: "Tom Curran", role: "All-Rounder", overseas: true, nat: "England" },
  { name: "Mohammad Nabi", role: "All-Rounder", overseas: true, nat: "Afghanistan" },
  { name: "Gulbadin Naib", role: "All-Rounder", overseas: true, nat: "Afghanistan" },
  { name: "Sikandar Raza", role: "All-Rounder", overseas: true, nat: "Zimbabwe" },
  { name: "Johnson Charles", role: "Batsman", overseas: true, nat: "West Indies" },
  { name: "Litton Das", role: "Wicketkeeper", overseas: true, nat: "Bangladesh" },
  { name: "Tom Latham", role: "Wicketkeeper", overseas: true, nat: "New Zealand" },
  { name: "Kyle Verreynne", role: "Wicketkeeper", overseas: true, nat: "South Africa" },
  { name: "Richard Gleeson", role: "Bowler", overseas: true, nat: "England" },
  { name: "Josh Little", role: "Bowler", overseas: true, nat: "Ireland" },
  { name: "Lizaad Williams", role: "Bowler", overseas: true, nat: "South Africa" },
  { name: "Luke Wood", role: "Bowler", overseas: true, nat: "England" },
  { name: "Towhid Hridoy", role: "Batsman", overseas: true, nat: "Bangladesh" },
  { name: "Mikyle Louis", role: "Batsman", overseas: true, nat: "West Indies" },
  { name: "Harry Tector", role: "Batsman", overseas: true, nat: "Ireland" },
  { name: "Rassie van der Dussen", role: "Batsman", overseas: true, nat: "South Africa" },
  { name: "Will Young", role: "Batsman", overseas: true, nat: "New Zealand" },
  { name: "Najibullah Zadran", role: "Batsman", overseas: true, nat: "Afghanistan" },
  { name: "Ibrahim Zadran", role: "Batsman", overseas: true, nat: "Afghanistan" },
  { name: "Jason Behrendorff", role: "Bowler", overseas: true, nat: "Australia" },
  { name: "Jacob Bethell", role: "All-Rounder", overseas: true, nat: "England" },
  { name: "Brydon Carse", role: "All-Rounder", overseas: true, nat: "England" },
  { name: "Aaron Hardie", role: "All-Rounder", overseas: true, nat: "Australia" },
  { name: "Kyle Mayers", role: "All-Rounder", overseas: true, nat: "West Indies" },
  { name: "Kamindu Mendis", role: "All-Rounder", overseas: true, nat: "Sri Lanka" },
  { name: "Matthew Short", role: "All-Rounder", overseas: true, nat: "Australia" },
  { name: "Dushmantha Chameera", role: "Bowler", overseas: true, nat: "Sri Lanka" },
  { name: "Nathan Ellis", role: "Bowler", overseas: true, nat: "Australia" },
  { name: "Shamar Joseph", role: "Bowler", overseas: true, nat: "West Indies" },
  { name: "Jhye Richardson", role: "Bowler", overseas: true, nat: "Australia" },
  { name: "Tim Southee", role: "Bowler", overseas: true, nat: "New Zealand" },
  { name: "Shakib Al Hasan", role: "All-Rounder", overseas: true, nat: "Bangladesh" },
  { name: "Mehidy Hasan Miraz", role: "All-Rounder", overseas: true, nat: "Bangladesh" },
  { name: "Dasun Shanaka", role: "All-Rounder", overseas: true, nat: "Sri Lanka" },
  { name: "Shoriful Islam", role: "Bowler", overseas: true, nat: "Bangladesh" },
  { name: "Qais Ahmad", role: "Bowler", overseas: true, nat: "Afghanistan" },
  { name: "Charith Asalanka", role: "All-Rounder", overseas: true, nat: "Sri Lanka" },
  { name: "George Garton", role: "Bowler", overseas: true, nat: "England" },
  { name: "Daniel Mousley", role: "All-Rounder", overseas: true, nat: "England" },
  { name: "Jamie Overton", role: "All-Rounder", overseas: true, nat: "England" },
  { name: "Dunith Wellalage", role: "All-Rounder", overseas: true, nat: "Sri Lanka" },
  { name: "Ottneil Baartman", role: "Bowler", overseas: true, nat: "South Africa" },
  { name: "Xavier Bartlett", role: "Bowler", overseas: true, nat: "Australia" },
  { name: "Dilshan Madushanka", role: "Bowler", overseas: true, nat: "Sri Lanka" },
  { name: "Adam Milne", role: "Bowler", overseas: true, nat: "New Zealand" },
  { name: "William O'Rourke", role: "Bowler", overseas: true, nat: "New Zealand" },
  { name: "Ollie Pope", role: "Batsman", overseas: true, nat: "England" },
  { name: "Andre Fletcher", role: "Wicketkeeper", overseas: true, nat: "West Indies" },
  { name: "Leus Du Plooy", role: "Batsman", overseas: true, nat: "South Africa" },
  { name: "Michael Pepper", role: "Wicketkeeper", overseas: true, nat: "England" },
  { name: "Allah Ghazanfar", role: "Bowler", overseas: true, nat: "Afghanistan" },
  { name: "Akeal Hosein", role: "Bowler", overseas: true, nat: "West Indies" },
  { name: "Mujeeb Ur Rahman", role: "Bowler", overseas: true, nat: "Afghanistan" },
  { name: "Waqar Salamkheil", role: "Bowler", overseas: true, nat: "Afghanistan" },
  { name: "Tom Kohler-Cadmore", role: "Wicketkeeper", overseas: true, nat: "England" },
  { name: "Jordan Cox", role: "Wicketkeeper", overseas: true, nat: "England" },
  { name: "Ali Khan", role: "Bowler", overseas: true, nat: "USA" },
  { name: "Nqabayomzi Peter", role: "Bowler", overseas: true, nat: "South Africa" },
  // ─── Additional domestic Indian players from IPL 2025 longlist ───
  { name: "Smaran Ravichandran", role: "Batsman", overseas: false },
  { name: "Andre Siddharth", role: "Batsman", overseas: false },
  { name: "Avineesh Sudha", role: "All-Rounder", overseas: false },
  { name: "L.R Chethan", role: "Wicketkeeper", overseas: false },
  { name: "Aryaman Singh Dhaliwal", role: "Wicketkeeper", overseas: false },
  { name: "Sanskar Rawat", role: "Wicketkeeper", overseas: false },
  { name: "Bipin Saurabh", role: "Wicketkeeper", overseas: false },
  { name: "Tanay Thyagarajan", role: "Bowler", overseas: false },
  { name: "Raghav Goyal", role: "Bowler", overseas: false },
  { name: "Roshan Waghsare", role: "All-Rounder", overseas: false },
  { name: "Bailapudi Yeswanth", role: "Batsman", overseas: false },
  { name: "Ashwin Hebbar", role: "Batsman", overseas: false },
  { name: "Rohan Kunnummal", role: "Batsman", overseas: false },
  { name: "Ayush Pandey", role: "Batsman", overseas: false },
  { name: "Akshat Raghuwanshi", role: "Batsman", overseas: false },
  { name: "Shaoun Roger", role: "All-Rounder", overseas: false },
  { name: "Virat Singh", role: "Batsman", overseas: false },
  { name: "Ajitesh Guruswamy", role: "Wicketkeeper", overseas: false },
  { name: "Vishnu Solanki", role: "Wicketkeeper", overseas: false },
  { name: "Prithvi Raj Yarra", role: "All-Rounder", overseas: false },
  { name: "Jasmer Dhankhar", role: "Bowler", overseas: false },
  { name: "Saumy Pandey", role: "Bowler", overseas: false },
  { name: "Tejasvi Dahiya", role: "Batsman", overseas: false },
  { name: "Sumit Ghadigaonkar", role: "All-Rounder", overseas: false },
  { name: "Bhagmender Lather", role: "All-Rounder", overseas: false },
  { name: "Emanjot Singh Chahal", role: "All-Rounder", overseas: false },
  { name: "Manvanth Kumar L", role: "All-Rounder", overseas: false },
  { name: "Sonu Yadav", role: "Bowler", overseas: false },
  { name: "S. Rithik Easwaran", role: "Batsman", overseas: false },
  { name: "Prahlad Singh", role: "All-Rounder", overseas: false },
  { name: "Karteek Sharma", role: "Bowler", overseas: false },
  { name: "Tejasvi Singh", role: "Wicketkeeper", overseas: false },
  { name: "Salman Nizar", role: "All-Rounder", overseas: false },
  { name: "Aniket Verma", role: "Batsman", overseas: false },
  { name: "Sumeet Verma", role: "Bowler", overseas: false },
  { name: "Amandeep Khare", role: "Batsman", overseas: false },
  { name: "Mujtaba Yousuf", role: "All-Rounder", overseas: false },
  { name: "Ripal Patel", role: "Batsman", overseas: false },
  { name: "Sheldon Jackson", role: "Wicketkeeper", overseas: false },
  { name: "Wakhare Aditya", role: "Bowler", overseas: false },
  { name: "Tushar Raheja", role: "Wicketkeeper", overseas: false },
  { name: "Saurabh Kumar", role: "All-Rounder", overseas: false },
  { name: "Yarra Prithviraj", role: "Bowler", overseas: false },
  { name: "Pratham Harshal", role: "Batsman", overseas: false },
  { name: "Aryan Varma", role: "Batsman", overseas: false },
  { name: "Rohan Rana", role: "All-Rounder", overseas: false },
  { name: "Parvez Alam", role: "Bowler", overseas: false },
  { name: "Gaurav Kumar", role: "Bowler", overseas: false },
  { name: "Sachin Rana", role: "All-Rounder", overseas: false },
  { name: "Dhiraj Kumar", role: "Batsman", overseas: false },
  { name: "Randhir Singh", role: "All-Rounder", overseas: false },
  { name: "Akshay Jain", role: "Bowler", overseas: false },
  { name: "Pawan Negi", role: "All-Rounder", overseas: false },
  { name: "Monu Kumar", role: "Bowler", overseas: false },
  { name: "Mihir Hirwani", role: "Bowler", overseas: false },
  { name: "Puneet Bisht", role: "Wicketkeeper", overseas: false },
  { name: "Aditya Sarwate", role: "All-Rounder", overseas: false },
  { name: "Shubhang Hegde", role: "All-Rounder", overseas: false },
  { name: "Akshath Reddy", role: "Batsman", overseas: false },
  { name: "Tanmay Srivastava", role: "Batsman", overseas: false },
  { name: "Smit Patel", role: "Wicketkeeper", overseas: false },
  { name: "Siddhesh Lad", role: "Batsman", overseas: false },
  { name: "Jalaj Saxena", role: "All-Rounder", overseas: false },
  { name: "Satyajeet Bachhav", role: "Bowler", overseas: false },
  { name: "Anirudh Singh", role: "All-Rounder", overseas: false },
  { name: "Ravi Yadav", role: "Bowler", overseas: false },
  { name: "Shreevats Goswami", role: "Wicketkeeper", overseas: false },
  { name: "Yash Lalwani", role: "Batsman", overseas: false },
  { name: "Tushar Deshpande", role: "Bowler", overseas: false },
  { name: "Shahid Judge", role: "All-Rounder", overseas: false },
  { name: "Deep Dasgupta Jr", role: "Wicketkeeper", overseas: false },
  { name: "Rohan Prem", role: "Batsman", overseas: false },
  { name: "Pradeep Sahu", role: "All-Rounder", overseas: false },
  { name: "Gaurav Yadav", role: "Bowler", overseas: false },
  { name: "Yuvraj Tomar", role: "Batsman", overseas: false },
  { name: "Siddhant Lohani", role: "All-Rounder", overseas: false },
  { name: "Dev Uthappa", role: "Wicketkeeper", overseas: false },
  { name: "Anand Rajan", role: "Bowler", overseas: false },
  { name: "Gaurav Sundararaman", role: "Batsman", overseas: false },
  { name: "Krish Yadav", role: "All-Rounder", overseas: false },
  { name: "Taruwar Kohli", role: "Batsman", overseas: false },
  { name: "Shreyansh Sharma", role: "All-Rounder", overseas: false },
  { name: "Manveer Singh", role: "Batsman", overseas: false },
  { name: "Prashant Gupta", role: "Batsman", overseas: false },
  { name: "Govind Sharma", role: "All-Rounder", overseas: false },
  { name: "Deepanshu Singh", role: "Bowler", overseas: false },
  { name: "Pratham Singh", role: "Batsman", overseas: false },
  { name: "Anuj Tomar", role: "All-Rounder", overseas: false },
  { name: "Tushar Bharadwaj", role: "Bowler", overseas: false },
  { name: "Lakshay Thareja", role: "Batsman", overseas: false },
  { name: "Vedant Mehta", role: "Batsman", overseas: false },
  { name: "Ayushman Gupta", role: "Wicketkeeper", overseas: false },
  { name: "Sahaj Patel", role: "Bowler", overseas: false },
  { name: "Rajneesh Gurbani", role: "Bowler", overseas: false },
  { name: "Raunak Chauhan", role: "All-Rounder", overseas: false },
  { name: "Vaibhav Rawal", role: "Batsman", overseas: false },
  { name: "Nikin Jose", role: "Batsman", overseas: false },
  { name: "Harsh Dubey", role: "Bowler", overseas: false },
  { name: "Saurabh Rawat", role: "Batsman", overseas: false },
  { name: "Aditya Thakare", role: "Bowler", overseas: false },
  { name: "Roosh Kalaria", role: "Bowler", overseas: false },
  { name: "Chirag Jani", role: "All-Rounder", overseas: false },
  { name: "Parth Bhut", role: "Bowler", overseas: false },
  { name: "Het Patel", role: "All-Rounder", overseas: false },
  { name: "C Hari Nishaanth", role: "Batsman", overseas: false },
  { name: "Jhon Osafa", role: "Bowler", overseas: false },
  { name: "Kiran Akash", role: "Batsman", overseas: false },
  { name: "Sanjay Yadav", role: "All-Rounder", overseas: false },
  { name: "Atit Sheth", role: "All-Rounder", overseas: false },
  { name: "Robin Bist", role: "Batsman", overseas: false },
  { name: "Anureet Singh", role: "Bowler", overseas: false },
  { name: "Arjit Gupta", role: "Wicketkeeper", overseas: false },
  { name: "Rahul Sharma", role: "Bowler", overseas: false },
  { name: "Vivrant Sharma", role: "Batsman", overseas: false },
  { name: "Dewald Brevis Jr", role: "Batsman", overseas: false },
  { name: "Kevin Koththigoda", role: "Bowler", overseas: true, nat: "Sri Lanka" },
  { name: "Nuwan Pradeep", role: "Bowler", overseas: true, nat: "Sri Lanka" },
  { name: "Devon Thomas", role: "Wicketkeeper", overseas: true, nat: "West Indies" },
  { name: "Angelo Mathews", role: "All-Rounder", overseas: true, nat: "Sri Lanka" },
  { name: "Oshane Thomas", role: "Bowler", overseas: true, nat: "West Indies" },
  { name: "Carlos Brathwaite", role: "All-Rounder", overseas: true, nat: "West Indies" },
  { name: "Obed McCoy", role: "Bowler", overseas: true, nat: "West Indies" },
  { name: "Fabian Allen", role: "All-Rounder", overseas: true, nat: "West Indies" },
  { name: "Sheldon Cottrell", role: "Bowler", overseas: true, nat: "West Indies" },
  { name: "Sandeep Lamichhane", role: "Bowler", overseas: true, nat: "Nepal" },
  { name: "Blessing Muzarabani", role: "Bowler", overseas: true, nat: "Zimbabwe" },
  { name: "Sean Williams", role: "All-Rounder", overseas: true, nat: "Zimbabwe" },
  { name: "Ryan Burl", role: "All-Rounder", overseas: true, nat: "Zimbabwe" },
  { name: "Craig Ervine", role: "Batsman", overseas: true, nat: "Zimbabwe" },
  { name: "Taskin Ahmed", role: "Bowler", overseas: true, nat: "Bangladesh" },
  { name: "Tanzid Hasan", role: "Batsman", overseas: true, nat: "Bangladesh" },
  { name: "Mahmudullah", role: "All-Rounder", overseas: true, nat: "Bangladesh" },
  { name: "Afif Hossain", role: "All-Rounder", overseas: true, nat: "Bangladesh" },
  { name: "Soumya Sarkar", role: "All-Rounder", overseas: true, nat: "Bangladesh" },
  { name: "Hazratullah Zazai", role: "Batsman", overseas: true, nat: "Afghanistan" },
  { name: "Karim Janat", role: "All-Rounder", overseas: true, nat: "Afghanistan" },
  { name: "Naveen-ul-Hasan", role: "Bowler", overseas: true, nat: "Afghanistan" },
  { name: "Zahir Khan", role: "Bowler", overseas: true, nat: "Afghanistan" },
  { name: "Ryan ten Doeschate", role: "All-Rounder", overseas: true, nat: "Netherlands" },
  { name: "Ben Cutting", role: "All-Rounder", overseas: true, nat: "Australia" },
  { name: "Chris Jordan", role: "Bowler", overseas: true, nat: "England" },
  { name: "Jofra Archer", role: "Bowler", overseas: true, nat: "England" },
  { name: "Mark Wood", role: "Bowler", overseas: true, nat: "England" },
  { name: "Dawid Malan", role: "Batsman", overseas: true, nat: "England" },
  { name: "Alex Hales", role: "Batsman", overseas: true, nat: "England" },
  { name: "Jason Roy", role: "Batsman", overseas: true, nat: "England" },
  { name: "Chris Woakes", role: "All-Rounder", overseas: true, nat: "England" },
  { name: "Olly Stone", role: "Bowler", overseas: true, nat: "England" },
  { name: "Sean Abbott", role: "All-Rounder", overseas: true, nat: "Australia" },
  { name: "Cameron Green", role: "All-Rounder", overseas: true, nat: "Australia" },
  { name: "Riley Meredith", role: "Bowler", overseas: true, nat: "Australia" },
  { name: "Daniel Sams", role: "All-Rounder", overseas: true, nat: "Australia" },
  { name: "Chris Lynn", role: "Batsman", overseas: true, nat: "Australia" },
  { name: "Ben Dwarshuis", role: "Bowler", overseas: true, nat: "Australia" },
  { name: "Tye Abell", role: "Bowler", overseas: true, nat: "Australia" },
  { name: "Dwayne Bravo", role: "All-Rounder", overseas: true, nat: "West Indies" },
  { name: "Sunil Narine", role: "All-Rounder", overseas: true, nat: "West Indies" },
  { name: "Andre Russell", role: "All-Rounder", overseas: true, nat: "West Indies" },
  { name: "Nicholas Pooran", role: "Wicketkeeper", overseas: true, nat: "West Indies" },
  { name: "Shimron Hetmyer", role: "Batsman", overseas: true, nat: "West Indies" },
  { name: "Odean Smith", role: "All-Rounder", overseas: true, nat: "West Indies" },
  { name: "Heinrich Klaasen Jr", role: "Batsman", overseas: true, nat: "South Africa" },
  { name: "Wayne Parnell", role: "All-Rounder", overseas: true, nat: "South Africa" },
  { name: "Sisanda Magala", role: "Bowler", overseas: true, nat: "South Africa" },
  { name: "Marco Marais", role: "Batsman", overseas: true, nat: "South Africa" },
  { name: "George Linde", role: "All-Rounder", overseas: true, nat: "South Africa" },
  { name: "Dane Paterson", role: "Bowler", overseas: true, nat: "South Africa" },
  { name: "Darren Bravo", role: "Batsman", overseas: true, nat: "West Indies" },
  { name: "Hayden Walsh Jr", role: "Bowler", overseas: true, nat: "West Indies" },
  { name: "Michael Neser", role: "All-Rounder", overseas: true, nat: "Australia" },
  { name: "Kyle Jamieson", role: "All-Rounder", overseas: true, nat: "New Zealand" },
  { name: "Ish Sodhi", role: "Bowler", overseas: true, nat: "New Zealand" },
  { name: "Jimmy Neesham", role: "All-Rounder", overseas: true, nat: "New Zealand" },
  { name: "Colin Munro", role: "Batsman", overseas: true, nat: "New Zealand" },
  { name: "Martin Guptill", role: "Batsman", overseas: true, nat: "New Zealand" },
  { name: "Dhananjaya de Silva", role: "All-Rounder", overseas: true, nat: "Sri Lanka" },
  { name: "Lahiru Kumara", role: "Bowler", overseas: true, nat: "Sri Lanka" },
  { name: "Avishka Fernando", role: "Batsman", overseas: true, nat: "Sri Lanka" },
  { name: "Isuru Udana", role: "All-Rounder", overseas: true, nat: "Sri Lanka" },
];

// ═══════════════════════════════════════════════════════════════
// Stats generation helpers
// ═══════════════════════════════════════════════════════════════
function rand(min, max) {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

function randFloat(min, max, decimals = 2) {
  return parseFloat((Math.random() * (max - min) + min).toFixed(decimals));
}

function generateStats(role, tier) {
  const matchMultiplier = tier === 'Marquee' ? 3 : tier === 'A' ? 2 : tier === 'B' ? 1.5 : 1;
  const matches = rand(Math.floor(10 * matchMultiplier), Math.floor(120 * matchMultiplier));
  
  const stats = {
    matches,
    runs: 0, battingAvg: 0, strikeRate: 0,
    wickets: 0, bowlingAvg: 0, economy: 0,
    catches: rand(2, Math.floor(matches * 0.4)),
    fifties: 0, hundreds: 0
  };

  const isBatter = ['Batsman', 'Wicketkeeper', 'All-Rounder'].includes(role);
  const isBowler = ['Bowler', 'All-Rounder'].includes(role);

  if (isBatter) {
    stats.runs = rand(Math.floor(matches * 8), Math.floor(matches * 28));
    stats.battingAvg = randFloat(18, 42);
    stats.strikeRate = randFloat(115, 160);
    stats.fifties = Math.floor(stats.runs / 280);
    stats.hundreds = Math.floor(stats.runs / 1200);
  }

  if (isBowler) {
    stats.wickets = rand(Math.floor(matches * 0.3), Math.floor(matches * 1.1));
    stats.bowlingAvg = randFloat(20, 35);
    stats.economy = randFloat(7.0, 9.5);
  }

  return stats;
}

// ═══════════════════════════════════════════════════════════════
// Build the full dataset
// ═══════════════════════════════════════════════════════════════
const allPlayers = [];
const seenNames = new Set();

// 1. Add marquee players (stats already set)
for (const p of marqueePlayers) {
  if (seenNames.has(p.name)) continue;
  seenNames.add(p.name);
  allPlayers.push(p);
}

// 2. Add tier A players
for (const p of tierAPlayers) {
  if (seenNames.has(p.name)) continue;
  seenNames.add(p.name);
  allPlayers.push({
    name: p.name,
    nationality: p.overseas ? (p.nat || 'Overseas') : 'India',
    isOverseas: p.overseas,
    role: p.role,
    specialization: p.spec || p.role,
    basePrice: rand(100, 200),
    tier: 'A',
    stats: generateStats(p.role, 'A')
  });
}

// 3. Add tier B players
for (const p of tierBNames) {
  if (seenNames.has(p.name)) continue;
  seenNames.add(p.name);
  allPlayers.push({
    name: p.name,
    nationality: p.overseas ? (p.nat || 'Overseas') : 'India',
    isOverseas: p.overseas,
    role: p.role,
    specialization: p.spec || p.role,
    basePrice: rand(50, 100),
    tier: 'B',
    stats: generateStats(p.role, 'B')
  });
}

// 4. Add tier C players
for (const p of tierCNames) {
  if (seenNames.has(p.name)) continue;
  seenNames.add(p.name);

  const specs = {
    Batsman: ['Right-hand Bat', 'Left-hand Bat'],
    Bowler: ['Right-arm Fast', 'Right-arm Medium', 'Right-arm Spin', 'Left-arm Fast', 'Left-arm Spin'],
    'All-Rounder': ['Right-hand Bat, Right-arm Medium', 'Left-hand Bat, Left-arm Spin', 'Right-hand Bat, Right-arm Spin'],
    Wicketkeeper: ['Right-hand Bat, WK', 'Left-hand Bat, WK']
  };

  allPlayers.push({
    name: p.name,
    nationality: p.overseas ? (p.nat || 'Overseas') : 'India',
    isOverseas: p.overseas,
    role: p.role,
    specialization: p.spec || specs[p.role]?.[rand(0, specs[p.role].length - 1)] || p.role,
    basePrice: rand(20, 50),
    tier: 'C',
    stats: generateStats(p.role, 'C')
  });
}

// ═══════════════════════════════════════════════════════════════
// Write
// ═══════════════════════════════════════════════════════════════
const outputPath = path.join(__dirname, '..', 'data', 'players.json');
fs.writeFileSync(outputPath, JSON.stringify(allPlayers, null, 2));

console.log(`Done! Generated ${allPlayers.length} players`);
console.log(`  Marquee: ${allPlayers.filter(p => p.tier === 'Marquee').length}`);
console.log(`  Tier A:  ${allPlayers.filter(p => p.tier === 'A').length}`);
console.log(`  Tier B:  ${allPlayers.filter(p => p.tier === 'B').length}`);
console.log(`  Tier C:  ${allPlayers.filter(p => p.tier === 'C').length}`);
console.log(`  Indian:  ${allPlayers.filter(p => !p.isOverseas).length}`);
console.log(`  Overseas: ${allPlayers.filter(p => p.isOverseas).length}`);
